person/routes.py
import os
from typing import Optional, Dict

from flask import (
    Blueprint, request,
    render_template, current_app,
    session, redirect, url_for
)

from access import login_required
from database.operations import select_dict
from database.sql_provider import SQLProvider


blueprint_person = Blueprint('bp_person', __name__, template_folder='templates', static_folder="static")
provider = SQLProvider(os.path.join(os.path.dirname(__file__), 'sql'))


# Обрабатываем страницу с информацией о пользователе.
@blueprint_person.route('/<string:user_login>', methods=['GET', 'POST'])
# @login_required
def person(user_login):
    if request.method == 'GET':
        # print("session[role]: ", session["role"])
        role = get_role(user_login)

        if role == "doctor":
            return render_template('person.html', session=session, person=render_doctor(user_login))
        if role == "patient":
            return render_template('person.html', session=session, person=render_patient(user_login))
        if role == "registrator":
            return "Страницы регистратора пока нет ;("

        return "Kek"
    else:
        return "LOL KEK ERROR"


def get_role(user_login):
    sql_for_role_from_doctor = provider.get("role_from_doctor.sql", login=user_login)
    role_from_doctor = select_dict(current_app.config['db_config'], sql_for_role_from_doctor)
    
    sql_for_patient_search = provider.get("patient_search.sql", login=user_login)
    patient_search = select_dict(current_app.config['db_config'], sql_for_patient_search)

    print("role_from_doctor:", role_from_doctor)
    print("patient_search", patient_search)

    if not role_from_doctor and not patient_search:  # Пользователь не найден.
        return ""
    elif not role_from_doctor:  # Пользователь - пациент.
        return "patient"
    else:  # Пользователь - доктор или регистратор.
        if len(role_from_doctor) > 1:
            print("ERROR: Больше одного человека с логином", user_login)
        return role_from_doctor[0]["role"]



def render_doctor(user_login):
    if request.method == 'GET':

        # Получаем информацию о текущем враче.
        sql_for_doctor = provider.get("doctor.sql", login=user_login)
        # print("sql_for_doctor:", sql_for_doctor)
        doctor = select_dict(current_app.config['db_config'], sql_for_doctor)
        # print("doctor:", doctor)

        # Превращаем массив докторов в одного доктора.
        if len(doctor) != 1:
            return "You have multiple doctors with the same login!"
        else:
            doctor = doctor[0]

        # Получаем информацию обо всех историях болезни текущего врача.
        sql_for_doctor_stories = provider.get("doctor_stories.sql", doctor_id=doctor["id_doctor"])
        # print("sql_for_doctor_stories:", sql_for_doctor_stories)
        doctor_stories = select_dict(current_app.config['db_config'], sql_for_doctor_stories)
        # print("doctor_stories:", doctor_stories)

        # Собираем в массив все нужные нам id историй болезни.
        story_ids = []
        for story in doctor_stories:
            story_ids.append(story["id_story"])

        # print("story_ids", story_ids)
        # Получаем информацию обо всех осмотрах текущего врача.
        # Превращаем лист в кортеж для того, чтобы заменить квадратные скобки на круглые.
        sql_for_doctor_surveys = provider.get("doctor_surveys.sql", story_ids=tuple(story_ids))
        # print("sql_for_doctor_surveys:", sql_for_doctor_surveys)
        doctor_surveys = select_dict(current_app.config['db_config'], sql_for_doctor_surveys)
        # print("doctor_surveys:", doctor_surveys)

        # Хитро склеиваем все предыдущие результаты в единый словарь.
        doctor["stories"] = []
        for story in doctor_stories:
            story["surveys"] = []
            for survey in doctor_surveys:
                if story["id_story"] == survey["survey_story"]:
                    story["surveys"].append(survey)
            doctor["stories"].append(story)

        # print("doctor:", doctor)

        # Добавляем к данным о враче его фотографию.
        doctor["image"] = url_for("static", filename="user_photos") + "/" + doctor["image"]

        for story in doctor["stories"]:
            # Добавляем к данным об историях фото лечащих врачей.
            story["patient_image"] = url_for("static", filename="user_photos") + "/" + story["patient_image"]
            # Добавляем к данным о пациенте информацию о его местонахождении.
            story["location"] = str(story["id_department"]) + "-" + str(story["id_ward"])

        return doctor
    else:
        return "LOL KEK ERROR"


# Обрабатываем страницу с информаций о пациенте.
def render_patient(user_login):
    # Получаем информацию о текущем пациенте.
    sql_for_patient = provider.get("patient.sql", login=user_login)
    # print("sql_for_patient:", sql_for_patient)
    patient = select_dict(current_app.config['db_config'], sql_for_patient)
    # print("patient:", patient)

    # Получаем информацию обо всех историях болезни текущего пациента.
    sql_for_patient_stories = provider.get("patient_stories.sql", login=user_login)
    # print("sql_for_patient_stories:", sql_for_patient_stories)
    patient_stories = select_dict(current_app.config['db_config'], sql_for_patient_stories)
    # print("patient_stories:", patient_stories)

    # Получаем информацию обо всех осмотрах текущего пациента.
    sql_for_patient_surveys = provider.get("patient_surveys.sql", login=user_login)
    # print("sql_for_patient_surveys:", sql_for_patient_surveys)
    patient_surveys = select_dict(current_app.config['db_config'], sql_for_patient_surveys)
    # print("patient_surveys:", patient_surveys)

    # Превращаем массив пациентов в одного пациента.
    if len(patient) != 1:
        return "You have multiple patients with the same login!"
    else:
        patient = patient[0]

    # Хитро склеиваем все предыдущие результаты в единый словарь.
    patient["stories"] = []
    for story in patient_stories:
        story["surveys"] = []
        for survey in patient_surveys:
            if story["id_story"] == survey["survey_story"]:
                story["surveys"].append(survey)
        patient["stories"].append(story)

    # Добавляем к данным о пациенте информацию о его местонахождении.
    sql_for_location = provider.get("patient_location.sql", id_patient=patient["id_patient"])
    location = select_dict(current_app.config['db_config'], sql_for_location)
    # print("location:", location)
    if location:
        if len(location) != 1:
            return "This patient is in two locations simultaneously"
        location = location[0]  # Человек может находиться только в одной палате одновременно.
        patient["location"] = str(location["id_department"]) + "-" + str(location["id_ward"])

    # Добавляем к данным о пациенте его фотографию.
    patient["image"] = url_for("static", filename="user_photos") + "/" + patient["image"]

    for story in patient["stories"]:
        # Добавляем к данным об историях фото лечащих врачей.
        story["image"] = url_for("static", filename="user_photos") + "/" + story["image"]
        # Добавляем к данным о пациенте информацию о его местонахождении.
        story["location"] = str(story["id_department"]) + "-" + str(story["id_ward"])

    # Для единообразия фронтенда добавляем пациенту роль.
    patient["role"] = "patient"

    # print("patient: ", patient)

    return patient


# Обрабатываем страницу настроек.
@blueprint_person.route('/<string:user_login>/settings', methods=['GET', 'POST'])
def settings(user_login):
    if request.method == 'GET':
        if session["role"] == "doctor" or session["role"] == "registrator":
            return render_template("settings.html", session=session, person=render_doctor(user_login))
        if session["role"] == "patient":
            return render_template('settings.html', session=session, person=render_patient(user_login))
    else:
        return "LOL KEK ERROR"

ward/routes.py
import os
from typing import Optional, Dict

from flask import (
    Blueprint, request,
    render_template, current_app,
    session, redirect, url_for
)

from access import group_required
from database.operations import select_dict, select
from database.sql_provider import SQLProvider


blueprint_ward = Blueprint('bp_ward', __name__, template_folder='templates', static_folder='static')
provider = SQLProvider(os.path.join(os.path.dirname(__file__), 'sql'))


# Обрабатываем страницу с информацией о конкретной палате.
@blueprint_ward.route('/<int:department_id>-<int:ward_id>', methods=['GET', 'POST'])
@group_required
def specific_ward(department_id, ward_id):
    # if session["role"] == "patient":
    #     return "Отказано в доступе"

    if request.method == 'GET':
        sql_for_ward = provider.get("ward.sql", id_ward=ward_id, id_department=department_id)
        # print("sql_for_stories:", sql_for_stories)
        ward = select_dict(current_app.config['db_config'], sql_for_ward)
        print("ward:", ward)
        if ward:
            # ward = ward[0]
            sql_for_occupancy = provider.get("occupancy.sql", id_ward=ward_id, id_department=department_id)
            # print("kek", select_dict(current_app.config['db_config'], sql_for_occupancy))
            ward[0]["occupancy"] = select_dict(current_app.config['db_config'], sql_for_occupancy)[0]["amount"]

        # Исправляем адреса для аватарок.
        for patient in ward:
            patient["image"] = url_for("static", filename="user_photos/" + patient["image"])
        print("ward:", ward)

        return render_template('ward.html', ward=ward, session=session)
    else:
        return "LOL KEK ERROR"


# Обрабатываем страницу с информацией о всех палатах
@blueprint_ward.route('/', methods=['GET', 'POST'])
@group_required
def wards_list():
    if session["login"] == "patient":
        return "Отказано в доступе"

    if request.method == 'GET':
        # Запрос, в котором мы получаем информацию о заполненности всех отделений.
        sql_for_departments_occupancy = provider.get("departments_occupancy.sql")
        # print("sql_for_stories:", sql_for_stories)
        departments_occupancy = select_dict(current_app.config['db_config'], sql_for_departments_occupancy)
        # print("departments_occupancy:", departments_occupancy)

        # Запрос, в котором мы получаем информацию о заполненности всех палат.
        sql_for_wards_occupancy = provider.get("wards_occupancy.sql")
        # print("sql_for_stories:", sql_for_stories)
        wards_occupancy = select_dict(current_app.config['db_config'], sql_for_wards_occupancy)
        # print("wards_occupancy:", wards_occupancy)
        
        # Запрос, в котором мы получаем информацию о главах каждого отделения.
        sql_for_departments_heads = provider.get("departments_heads.sql")
        # print("sql_for_stories:", sql_for_stories)
        departments_heads = select_dict(current_app.config['db_config'], sql_for_departments_heads)
        # print("departments_heads:", departments_heads)
        
        # Запрос, в котором мы получаем информацию о врачах каждого отделения.
        sql_for_departments_doctors = provider.get("departments_doctors.sql")
        # print("sql_for_stories:", sql_for_stories)
        departments_doctors = select_dict(current_app.config['db_config'], sql_for_departments_doctors)
        # print("departments_doctors:", departments_doctors)

        # Теперь хитро склеиваем все предыдущие результаты для того, чтобы передать всё на фронт одной переменной.
        departments = departments_occupancy
        for department in departments:
            # Приклеиваем информацию о палатах.
            department["wards"] = []
            for ward in wards_occupancy:
                if ward["id_department"] == department["id_department"]:
                    if not ward["ward_occupancy"]:  # Избавляемся от надписи None для пустых палат.
                        ward["ward_occupancy"] = 0
                    department["wards"].append(ward)
            # Приклеиваем информацию о главе департамента.
            for doctor in departments_doctors:
                if doctor["id_department"] == department["id_department"]:
                    department["department_head"] = doctor
            # Приклеиваем информацию о врачах отделения.
            department["doctors"] = []
            for doctor in departments_doctors:
                if doctor["id_department"] == department["id_department"]:
                    department["doctors"].append(doctor)

        # print("departments:", departments)

    return render_template('all_wards.html', departments=departments, session=session)

templates/access_denied.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Отказано в доступе</title>
    <link rel="stylesheet" href="{{ url_for('static', filename="base.css") }}">
    <link rel="stylesheet" href="{{ url_for('static', filename="access_denied.css") }}">
</head>
<body>

<div class="wrapper">
    <div class="access_denied">У вас нет прав на просмотр данной страницы ;(</div>
    <button  class="back-button flowing" type="button" onclick="history.back();" value="Вернуться назад">Вернуться назад</button>
</div>

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='plus.png') }}" type="image/x-icon">
</head>
<body>

<div class="container">
    <header class="header">
        <div class="header-inner-container">
            <span class="title" >
                <a href="/" class="plus-icon-container">
                    <img class="plus-icon" src="{{ url_for("static", filename="plus.png") }}">
                </a>
                <a class="title-text" href="{{ url_for("bp_ward.wards_list") }}">Hospital</a>
            </span>
            <div class="user-info">
                <a href="{{ url_for("bp_person.settings", user_login = session["login"]) }}" class="settings-icon-container">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon settings-icon" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065z"></path>
                        <circle cx="12" cy="12" r="3"></circle>
                    </svg>
                </a>
                <a class="user-name" href="{{ url_for("bp_person.person", user_login = session["login"]) }}">
                    {{ session["surname"] }}
                    {{ session["name"][0] }}.
                    {% if session["patronymic"][0] %}
                        {{ session["patronymic"][0] }}.
                    {% endif %}
                </a>
                <a href="{{ url_for('bp_auth.start_auth') }}" class="logout-container">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-logout" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                       <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                       <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2"></path>
                       <path d="M7 12h14l-3 -3m0 6l3 -3"></path>
                    </svg>
                </a>
            </div>
        </div>
    </header>

    <div class="content">
        {% block settings %}{% endblock %}
        {% block person %}{% endblock %}
        {% block ward %}{% endblock %}
        {% block all_wards %}{% endblock %}
        {% block dashboard %}{% endblock %}
    </div>
</div>



</body>
</html>

templates/dashboard.html
{% extends "base.html" %}

{% block dashboard %}

<title>Dashboard</title>
<link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css') }}">

<div class="main-title">Панель инструментов</div>



{% if session["role"] == "doctor" %}

<div class="make-survey-title mid-title">Провести осмотр</div>

<form class="make-survey-block" action="" method ="POST">
    <select name="id_patient" id="" class="patient-selection">
        {% for patient in active_patients %}
            <option value="{{ patient["id_patient"] }}">
                {{ patient["surname"] }}
                {{ patient["name"] }}
                {% if patient["patronymic"] %}
                    {{ patient["patronymic"] }}
                {% endif %}

                , Палата {{ patient["id_department"] }}-{{ patient["id_ward"] }},
                {{ patient["diagnosis"] }}
                {% if patient["story_doctor"] == session["id_doctor"] %}
                    <<========== Ваш пациент!
                {% endif %}
            </option>
        {% endfor %}
    </select>
    <textarea name="survey_text" placeholder="рекомендации и предписания" id="" cols="30" rows="10" class="survey-text-input"></textarea>
    <input type="submit" value="Отправить" class="make-survey-button">
    <input class="" type="hidden" name="is-survey-form" value="yes">
</form>


<div class="patients-container">
    <div class="patients-title">Ваши пациенты</div>
    {% for patient in doctor_active_patients %}
        <a href="/person/{{ patient["login"] }}" class="wrapping-link">
            <form class="patient-container flowing" action="" method ="POST">
                <div class="patient-card">
                    <img class="patient-photo" src="{{ patient["image"] }}">
                    <div class="patient-info">
                        <div class="patient-upper-line">
                            <span class="patient-name">
                                {{ patient["surname"] }}
                                {{ patient["name"] }}
                                {% if patient["patronymic"] %}
                                    {{ patient["patronymic"] }}
                                {% endif %}
                                <span class="patient-login">
                                    LOGIN: {{ patient["login"] }}
                                </span>
                            </span>
                            <span class="patient-location">
                                Палата {{ patient["location"] }}
                            </span>
                        </div>
                        <div class="patient-lower-line">
                            <span class="patient-diagnosis">
                                Диагноз: {{ patient["diagnosis"] }}
                            </span>
                            <span class="patient-reg-date">
                                Дата поступления: {{ patient["reg_date"] }}
                            </span>
                        </div>
                    </div>
                </div>

                <button name="id_patient" value="{{ patient["id_patient"] }}" class="discharge-button">
                    <svg xmlns="http://www.w3.org/2000/svg" class="check" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                       <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                       <path d="M5 12l5 5l10 -10"></path>
                    </svg>
                    <span>ВЫПИСАТЬ</span>
                </button>

                <input class="" type="hidden" name="is-discharge-form" value="yes">
            </form>
        </a>
    {% endfor %}
</div>



{% elif session["role"] == "registrator" %}

<div class="new-story-title mid-title">Добавить историю болезни</div>

<form class="add-story-block" action="" method ="POST">
    <select name="id_patient" id="" class="">
        {% for patient in patients %}
            <option value="{{ patient["id_patient"] }}">
                {{ patient["surname"] }}
                {{ patient["name"] }}
                {% if patient["patronymic"] %}
                    {{ patient["patronymic"] }}
                {% endif %}
                <span class="birth-date">{{ patient["birth_year"] }} г.р.</span>
            </option>
        {% endfor %}
    </select>
    <select name="id_doctor" id="" class="doctor-selection">
        {% for doctor in doctors %}
            <option value="{{ doctor["id_doctor"] }}">
                {{ doctor["surname"] }}
                {{ doctor["name"] }}
                {% if doctor["patronymic"] %}
                    {{ doctor["patronymic"] }}
                {% endif %},
                {{ doctor["specialization"] }}
                [
                {% if doctor["occupancy"] %}
                    {{ doctor["occupancy"] }}
                {% else %}
                    0
                {% endif %}
                Пациентов ]
            </option>
        {% endfor %}
    </select>
    <input type="text" class="diagnose-input" name="diagnosis" placeholder="Предварительный диагноз">
    <select name="id_ward" id="" class="ward-selection">
        {% for ward in wards %}
            <option value="{{ ward["id_ward"] }}">
                Палата
                {{ ward["id_department"] }}-{{ ward["id_ward"] }}
                [
                {% if ward["occupancy"] %}
                    {{ ward["occupancy"] }}
                {% else %}
                    0
                {% endif %}
                / {{ ward["capacity"] }}
                ]
            </option>
        {% endfor %}
    </select>

    <input type="submit" value="Отправить" class="add-story-button">
    <input class="" type="hidden" name="is-new-story-form" value="yes">
</form>

{% else %}

Панель инструментов для пациента в разработке

{% endif %}





{% endblock %}